#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perl6-Binding
version:      0.5
version_from: Binding.pm
installdirs:  site
requires:
    PadWalker:                     0.09
    Text::Balanced:                1.89
    Filter::Util::Call:            1.06

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
